# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "actions_menu", to: "actions_menu.js"
pin "copy_buttons", to: "copy_buttons.js"
pin "flash_messages", to: "flash_messages.js"
pin "folder_show", to: "folder_show.js"
pin "folders_index", to: "folders_index.js"
pin "mobile_nav", to: "mobile_nav.js"
pin "profile_dropdown", to: "profile_dropdown.js"
pin "recents_index", to: "recents_index.js"
pin "share_modal", to: "share_modal.js"
pin "share_links_new", to: "share_links_new.js"
pin "shared_with_me", to: "shared_with_me.js"
